import Config

# Configure your database
# Uploads OUTSIDE priv/static on purpose: in there the main endpoint Plug.Static
# intercepts the path before UploadsStatic and refuses the file for not being in
# its :only list, returning 400 for every upload in dev.
config :o_grupo_de_estudos, :uploads_path, Path.expand("../priv/uploads", __DIR__)

config :o_grupo_de_estudos, OGrupoDeEstudos.Repo,
  username: "forrozin",
  password: "forrozin",
  hostname: "localhost",
  port: 5433,
  database: "o_grupo_de_estudos_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :o_grupo_de_estudos, OGrupoDeEstudosWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "cZiOK7ReBYtt4HPe4PPtyDkcE2jXohnnIUAPPx/SImS+g+f3N8KOhFF9Eo0IiHRJ",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:o_grupo_de_estudos, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:o_grupo_de_estudos, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :o_grupo_de_estudos, OGrupoDeEstudosWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/o_grupo_de_estudos_web/router\.ex$"E,
      ~r"lib/o_grupo_de_estudos_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :o_grupo_de_estudos, dev_routes: true

# In dev, emails really go out through SMTP. Exception: recipients at @teste.com
# go to the local mailbox (/dev/mailbox).
#
# Put the credentials in the environment before starting the server:
#
#     export MAILER_HOST=smtp.yourdomain.com
#     export MAILER_USER=you@email.com
#     export MAILER_PASS=your_app_password
#
# For Gmail: generate an App Password at myaccount.google.com/apppasswords (it
# needs 2FA on). Port 587 with TLS already works.
config :o_grupo_de_estudos, OGrupoDeEstudos.Mailer,
  adapter: Swoosh.Adapters.SMTP,
  relay: System.get_env("MAILER_HOST", "smtp.gmail.com"),
  username: System.get_env("MAILER_USER"),
  password: System.get_env("MAILER_PASS"),
  tls: :always,
  port: 587

# Turns the filter on: @teste.com emails go to the local mailbox, not to real SMTP.
config :o_grupo_de_estudos, :filter_test_emails, true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
