defmodule OGrupoDeEstudosWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :o_grupo_de_estudos

  # The session is stored in a signed cookie: readable, but not tamperable.
  @session_options [
    store: :cookie,
    key: "_o_grupo_de_estudos_key",
    signing_salt: "cBOx9GwA",
    same_site: "Lax",
    max_age: 30 * 24 * 60 * 60
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # With code reloading disabled (production), `gzip` serves the compressed files
  # generated by `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :o_grupo_de_estudos,
    gzip: not code_reloading?,
    only: OGrupoDeEstudosWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Serves user uploads from the persistent volume in production, and from
  # priv/static/uploads in development.
  plug OGrupoDeEstudosWeb.Plugs.UploadsStatic

  if Mix.env() == :dev do
    plug Tidewave
  end

  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :o_grupo_de_estudos
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug OGrupoDeEstudosWeb.Router
end
